[package]
name = "woothee"
version = "0.1.0"
authors = ["hhatto <hhatto.jp@gmail.com>"]
license = "Apache-2.0"
license-file = "LICENSE"
repository = "https://github.com/hhatto/woothee-rust"
keywords = ["useragent", "ua"]
description = "user-agent strings parser"
documentaiton = "http://hhatto.github.io/woothee-rust/woothee/"

[dependencies]
regex = "0.1"
