[package]
name = "woothee"
version = "0.4.0"
authors = ["hhatto <hhatto.jp@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/hhatto/woothee-rust"
keywords = ["useragent", "ua"]
description = "user-agent strings parser"
documentation = "http://hhatto.github.io/woothee-rust/woothee/"
build = "build.rs"

[dependencies]
regex = "0.1"
lazy_static = "0.2.1"
clippy = { version = "0.0.79", optional = true }

[features]
default = []
generate = ["yaml-rust", "tera", "tempdir", "glob", "serde"]

[build-dependencies]
tera = { version = "0.1.1", optional = true }
yaml-rust = { version = "0.3.2", optional = true }
tempdir = { version = "0.3", optional = true }
glob = { version = "0.2.11", optional = true }
serde = { version = "0.7", optional = true }
